// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnhwhamhqslmqkvsfmth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuaHdoYW1ocXNsbXFrdnNmbXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzcxOTcsImV4cCI6MjA1ODc1MzE5N30.m0lgFeD5Py7nyelAwXgBGZ9LGK9qQXrs1xc6YY8SAJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);