// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scektcthypjkorwukxkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjZWt0Y3RoeXBqa29yd3VreGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDY1NjksImV4cCI6MjA1OTUyMjU2OX0.hnaVPzeILJeGsRLI6dvwGvpq4_y27UqJPKWOZAV84vM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);